/**
 *
 * $Id$
 */
package privacyModel.validation;

import java.util.Date;

import privacyModel.Principal;

/**
 * A sample validator interface for {@link privacyModel.AbstractPaper}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractPaperValidator {
	boolean validate();

	boolean validateProvidedBy(Principal value);

	boolean validateTerminationExplanation(String value);

	boolean validateStartDate(Date value);

	boolean validateTerminationDate(Date value);

	boolean validateLocation(String value);

	boolean validateDescription(String value);
}
