/**
 *
 * $Id$
 */
package privacyModel.validation;

import java.util.Date;

import privacyModel.AbstractComplaintAction;
import privacyModel.Principal;

/**
 * A sample validator interface for {@link privacyModel.Complaint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplaintValidator {
	boolean validate();

	boolean validateWho(Principal value);

	boolean validateWhen(Date value);

	boolean validateReason(String value);

	boolean validateAction(AbstractComplaintAction value);
}
