/**
 *
 * $Id$
 */
package privacyModel.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import privacyModel.PolicyStatement;
import privacyModel.Principal;

/**
 * A sample validator interface for {@link privacyModel.Denial}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DenialValidator {
	boolean validate();

	boolean validateWhen(Date value);

	boolean validateApprovedBy(Principal value);

	boolean validateReason(String value);

	boolean validateBasedOnStatements(EList<PolicyStatement> value);
}
