/**
 *
 * $Id$
 */
package privacyModel.validation;

import org.eclipse.emf.common.util.EList;

import privacyModel.Location;
import privacyModel.LocationType;

/**
 * A sample validator interface for {@link privacyModel.Location}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LocationValidator {
	boolean validate();

	boolean validateIsEUMember(boolean value);

	boolean validateType(LocationType value);

	boolean validateSubLocations(EList<Location> value);

	boolean validateLegalAgeLimit(int value);
}
