/**
 *
 * $Id$
 */
package privacyModel.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import privacyModel.NotificationInfo;
import privacyModel.NotificationType;
import privacyModel.Principal;

/**
 * A sample validator interface for {@link privacyModel.Notification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NotificationValidator {
	boolean validate();

	boolean validateType(NotificationType value);

	boolean validateNotifiers(EList<Principal> value);

	boolean validateReceivers(EList<Principal> value);

	boolean validateCausedBy(NotificationInfo value);

	boolean validateWhen(Date value);
}
