/**
 *
 * $Id$
 */
package privacyModel.validation;

import privacyModel.AbstractTime;
import privacyModel.Complaint;
import privacyModel.How;
import privacyModel.Principal;
import privacyModel.Purpose;
import privacyModel.What;
import privacyModel.Where;

/**
 * A sample validator interface for {@link privacyModel.PolicyStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PolicyStatementValidator {
	boolean validate();

	boolean validateWhen(AbstractTime value);

	boolean validateWho(Principal value);

	boolean validateWhy(Purpose value);

	boolean validateWhat(What value);

	boolean validateHow(How value);

	boolean validateWhose(Principal value);

	boolean validateWhom(Principal value);

	boolean validateWhere(Where value);

	boolean validateCausedBy(Complaint value);
}
