/**
 *
 * $Id$
 */
package privacyModel.validation;

import org.eclipse.emf.common.util.EList;

import privacyModel.ProcessingReason;
import privacyModel.ProcessingReasonSubtype;
import privacyModel.Purpose;

/**
 * A sample validator interface for {@link privacyModel.Purpose}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PurposeValidator {
	boolean validate();

	boolean validateProcessingReason(ProcessingReason value);

	boolean validateProcessingReasonSubtype(ProcessingReasonSubtype value);

	boolean validateSubPurposes(EList<Purpose> value);

	boolean validateDetails(String value);
}
