/**
 *
 * $Id$
 */
package privacyModel.validation;

import org.eclipse.emf.common.util.EList;

import privacyModel.PrivacyData;

/**
 * A sample validator interface for {@link privacyModel.SharedPrivacyData}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SharedPrivacyDataValidator {
	boolean validate();

	boolean validateAdditionalProtectionControls(EList<String> value);

	boolean validatePrivacydata(PrivacyData value);

	boolean validateColllectedFromSubject(boolean value);

	boolean validateDataSource(String value);
}
