/**
 *
 * $Id$
 */
package privacyModel.validation;

import java.util.Date;

import privacyModel.TimePreposition;

/**
 * A sample validator interface for {@link privacyModel.TimeStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimeStatementValidator {
	boolean validate();

	boolean validatePreposition(TimePreposition value);

	boolean validateDateTime(Date value);
}
