/**
 *
 * $Id$
 */
package privacyModel.validation;

import org.eclipse.emf.common.util.EList;

import privacyModel.Action;
import privacyModel.Provider;
import privacyModel.SharedPrivacyData;

/**
 * A sample validator interface for {@link privacyModel.What}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WhatValidator {
	boolean validate();

	boolean validateActions(EList<Action> value);

	boolean validateProviders(EList<Provider> value);

	boolean validateDatas(EList<SharedPrivacyData> value);
}
