/**
 *
 * $Id$
 */
package privacyModel.validation;

import privacyModel.Consent;

/**
 * A sample validator interface for {@link privacyModel.Withdraw}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WithdrawValidator {
	boolean validate();

	boolean validateSubject(Consent value);
}
