/**
 *
 * $Id$
 */
package oclstdlib.validation;

import org.eclipse.ocl.pivot.values.IntegerValue;

/**
 * A sample validator interface for {@link java.util.Collection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollectionValidator {
	boolean validate();

	boolean validateElementType(Object value);

	boolean validateLower(IntegerValue value);

	boolean validateUpper(IntegerValue value);
}
